#!/bin/sh
echo alert-pwm-measurement
sudo $(which node) alert-pwm-measurement
echo alert-trigger-pulse-measurement
sudo $(which node) alert-trigger-pulse-measurement
echo banked-leds
sudo $(which node) banked-leds
echo blinky
sudo $(which node) blinky
echo blinky-pwm
sudo $(which node) blinky-pwm
echo digital-read-performance
sudo $(which node) digital-read-performance
echo digital-write-performance
sudo $(which node) digital-write-performance
echo do-nothing
sudo $(which node) do-nothing
echo gpio-glitch-filter
sudo $(which node) gpio-glitch-filter
echo gpio-mode
sudo $(which node) gpio-mode
echo gpio-numbers
sudo $(which node) gpio-numbers
echo hardware-revision
sudo $(which node) hardware-revision
echo isr-enable-disable
sudo $(which node) isr-enable-disable
echo isr-multiple-sources
sudo $(which node) isr-multiple-sources
echo isr-performance
sudo $(which node) isr-performance
echo isr-timeouts
sudo $(which node) isr-timeouts
echo isr-timeouts-2
sudo $(which node) isr-timeouts-2
echo light-switch
sudo $(which node) light-switch
echo notifier
sudo $(which node) notifier
echo notifier-pwm
sudo $(which node) notifier-pwm
echo pull-up-down
sudo $(which node) pull-up-down
echo pulse-led
sudo $(which node) pulse-led
echo pwm
sudo $(which node) pwm
echo servo-control
sudo $(which node) servo-control
echo terminate
sudo $(which node) terminate
echo tick
sudo $(which node) tick
echo trigger-led
sudo $(which node) trigger-led
echo waves
sudo $(which node) waves
echo wave-add
sudo $(which node) wave-add
echo wave-chain
sudo $(which node) wave-chain

