#!/bin/sh
echo blinky
node blinky
echo do-nothing
node do-nothing
echo isr-performance
node isr-performance
echo isr-timeouts
node isr-timeouts
echo isr-timeouts-2
node isr-timeouts-2
echo light-switch
node light-switch
echo pull-up-down
node pull-up-down
echo pulse-led
node pulse-led
echo write-performance
node write-performance

